[supervisord]
nodaemon=true
user=root

[program:powerwatch]
command=python3 /usr/local/bin/powerwatch.py
startsecs=2
autorestart=true
stdout_logfile=/var/log/nut/powerwatch.log
stderr_logfile=/var/log/nut/powerwatch.err.log

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
